### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by mathiasbynens** [noprompt/frak#11]
It would be useful to have the Node version published on [npm](http://npmjs.org/), so people can just `npm install frak -g` and then just use the `frak` binary.

In the future, a non-binary version (that exports a `frak` function for use in other scripts) could be made available though `require('frak')`.

https://twitter.com/_munter_/status/388050796681891841 /cc @Munter

**Comment by captn3m0** [comment]
I went ahead and pushed a [frakjs package](https://www.npmjs.com/package/frakjs) to npm. The code (pretty bare-bones) is at https://github.com/captn3m0/frakjs. Supports both the binary and the export versions. 

In case anyone wants access to the package, let me know and I'll add you to the repo/package.

**Comment by mathiasbynens** [comment]
I’ve been using https://github.com/alexeld/regex-trie.

**Comment by mathiasbynens** [comment]
…and now there’s https://github.com/devongovett/regexgen as well.
